name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.4.0

      - name: Prepare .spoon directory for zipping
        run: |
          rm -rf .git .github

      - name: Zip Spoon directory
        run: |
          cd ..
          zip -r SimpleMicMute-${GITHUB_REF_NAME}.zip SimpleMicMute.spoon

      - name: Extract changelog for this release
        run: |
          awk "/^## \[${GITHUB_REF_NAME//./\\.}\]/ {flag=1; next} /^## \[/ && !/^## \[${GITHUB_REF_NAME//./\\.}\]/ {flag=0} flag" CHANGELOG.md > RELEASE_NOTES.md

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          body_path: RELEASE_NOTES.md
          draft: false
          files: ../SimpleMicMute-${{ github.ref_name }}.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
